apiVersion : apps/v1
kind: Deployment
metadata:
  name: "advserver"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "advserver"
  template:
    metadata:
      labels:
        app: "advserver"
    spec:
      containers:
        - name: "advserver"
          image: "ssscon.azurecr.io/advserver"
          ports:
          - containerPort: 80
