apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "advserver"
    labels:
        app: "advserver"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: advsrc-advserver.5a15826144ae4f289db5.eastus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "advserver"
                servicePort: 80
