apiVersion: v1
kind: Service
metadata:
    name: "advserver"
    labels:
        app: "advserver"
spec:
    type: ClusterIP
    ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      name: http
    selector:
        app: "advserver"
