on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ssscon.azurecr.io
        username: ${{ secrets.acr_ssscon_username }}
        password: ${{ secrets.acr_ssscon_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AdventureServer" -f  "AdventureServer/Dockerfile" -t ssscon.azurecr.io/sssaks:${{ github.sha }} --label dockerfile-path=AdventureServer/Dockerfile
        docker push ssscon.azurecr.io/sssaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sssaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep advsrc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace advsrc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: advsrc
        container-registry-url: ssscon.azurecr.io
        container-registry-username: ${{ secrets.acr_ssscon_username }}
        container-registry-password: ${{ secrets.acr_ssscon_password }}
        secret-name: sssaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: advsrc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          ssscon.azurecr.io/sssaks:${{ github.sha }}
        imagepullsecrets: |
          sssaksdockerauth
